version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "theBarberShop"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql